// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package runtime

import (
	"adm-num/ent/admnumber"
	"adm-num/ent/mststudent"
	"adm-num/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	admnumberFields := schema.AdmNumber{}.Fields()
	_ = admnumberFields
	// admnumberDescAdmStartNo is the schema descriptor for adm_start_no field.
	admnumberDescAdmStartNo := admnumberFields[0].Descriptor()
	// admnumber.DefaultAdmStartNo holds the default value on creation for the adm_start_no field.
	admnumber.DefaultAdmStartNo = admnumberDescAdmStartNo.Default.(string)
	// admnumberDescAdmCurrentNo is the schema descriptor for adm_current_no field.
	admnumberDescAdmCurrentNo := admnumberFields[1].Descriptor()
	// admnumber.DefaultAdmCurrentNo holds the default value on creation for the adm_current_no field.
	admnumber.DefaultAdmCurrentNo = admnumberDescAdmCurrentNo.Default.(string)
	// admnumberDescIsPrefixed is the schema descriptor for is_prefixed field.
	admnumberDescIsPrefixed := admnumberFields[2].Descriptor()
	// admnumber.DefaultIsPrefixed holds the default value on creation for the is_prefixed field.
	admnumber.DefaultIsPrefixed = admnumberDescIsPrefixed.Default.(bool)
	// admnumberDescPrefixStr is the schema descriptor for prefix_str field.
	admnumberDescPrefixStr := admnumberFields[3].Descriptor()
	// admnumber.DefaultPrefixStr holds the default value on creation for the prefix_str field.
	admnumber.DefaultPrefixStr = admnumberDescPrefixStr.Default.(string)
	// admnumberDescSuffixStr is the schema descriptor for suffix_str field.
	admnumberDescSuffixStr := admnumberFields[4].Descriptor()
	// admnumber.DefaultSuffixStr holds the default value on creation for the suffix_str field.
	admnumber.DefaultSuffixStr = admnumberDescSuffixStr.Default.(string)
	// admnumberDescSeparator is the schema descriptor for separator field.
	admnumberDescSeparator := admnumberFields[5].Descriptor()
	// admnumber.DefaultSeparator holds the default value on creation for the separator field.
	admnumber.DefaultSeparator = admnumberDescSeparator.Default.(string)
	// admnumberDescPrefillWithZero is the schema descriptor for prefill_with_zero field.
	admnumberDescPrefillWithZero := admnumberFields[6].Descriptor()
	// admnumber.DefaultPrefillWithZero holds the default value on creation for the prefill_with_zero field.
	admnumber.DefaultPrefillWithZero = admnumberDescPrefillWithZero.Default.(bool)
	// admnumberDescPrefillWidth is the schema descriptor for prefill_width field.
	admnumberDescPrefillWidth := admnumberFields[7].Descriptor()
	// admnumber.DefaultPrefillWidth holds the default value on creation for the prefill_width field.
	admnumber.DefaultPrefillWidth = admnumberDescPrefillWidth.Default.(int)
	// admnumber.PrefillWidthValidator is a validator for the "prefill_width" field. It is called by the builders before save.
	admnumber.PrefillWidthValidator = func() func(int) error {
		validators := admnumberDescPrefillWidth.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(prefill_width int) error {
			for _, fn := range fns {
				if err := fn(prefill_width); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	mststudentHooks := schema.MstStudent{}.Hooks()
	mststudent.Hooks[0] = mststudentHooks[0]
	mststudentFields := schema.MstStudent{}.Fields()
	_ = mststudentFields
	// mststudentDescFirstName is the schema descriptor for first_name field.
	mststudentDescFirstName := mststudentFields[0].Descriptor()
	// mststudent.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	mststudent.FirstNameValidator = mststudentDescFirstName.Validators[0].(func(string) error)
	// mststudentDescMiddleName is the schema descriptor for middle_name field.
	mststudentDescMiddleName := mststudentFields[1].Descriptor()
	// mststudent.DefaultMiddleName holds the default value on creation for the middle_name field.
	mststudent.DefaultMiddleName = mststudentDescMiddleName.Default.(string)
	// mststudentDescLastName is the schema descriptor for last_name field.
	mststudentDescLastName := mststudentFields[2].Descriptor()
	// mststudent.DefaultLastName holds the default value on creation for the last_name field.
	mststudent.DefaultLastName = mststudentDescLastName.Default.(string)
	// mststudentDescStdStudying is the schema descriptor for std_studying field.
	mststudentDescStdStudying := mststudentFields[3].Descriptor()
	// mststudent.DefaultStdStudying holds the default value on creation for the std_studying field.
	mststudent.DefaultStdStudying = mststudentDescStdStudying.Default.(bool)
	// mststudentDescStdStatus is the schema descriptor for std_status field.
	mststudentDescStdStatus := mststudentFields[4].Descriptor()
	// mststudent.DefaultStdStatus holds the default value on creation for the std_status field.
	mststudent.DefaultStdStatus = mststudentDescStdStatus.Default.(string)
	// mststudentDescStdSex is the schema descriptor for std_sex field.
	mststudentDescStdSex := mststudentFields[5].Descriptor()
	// mststudent.DefaultStdSex holds the default value on creation for the std_sex field.
	mststudent.DefaultStdSex = mststudentDescStdSex.Default.(string)
	// mststudentDescStdRegNo is the schema descriptor for std_reg_no field.
	mststudentDescStdRegNo := mststudentFields[6].Descriptor()
	// mststudent.DefaultStdRegNo holds the default value on creation for the std_reg_no field.
	mststudent.DefaultStdRegNo = mststudentDescStdRegNo.Default.(string)
	// mststudentDescStdAdmNo is the schema descriptor for std_adm_no field.
	mststudentDescStdAdmNo := mststudentFields[7].Descriptor()
	// mststudent.DefaultStdAdmNo holds the default value on creation for the std_adm_no field.
	mststudent.DefaultStdAdmNo = mststudentDescStdAdmNo.Default.(string)
	// mststudentDescStdDoa is the schema descriptor for std_doa field.
	mststudentDescStdDoa := mststudentFields[8].Descriptor()
	// mststudent.DefaultStdDoa holds the default value on creation for the std_doa field.
	mststudent.DefaultStdDoa = mststudentDescStdDoa.Default.(func() time.Time)
	// mststudentDescStdFresher is the schema descriptor for std_fresher field.
	mststudentDescStdFresher := mststudentFields[9].Descriptor()
	// mststudent.DefaultStdFresher holds the default value on creation for the std_fresher field.
	mststudent.DefaultStdFresher = mststudentDescStdFresher.Default.(bool)
	// mststudentDescStdDob is the schema descriptor for std_dob field.
	mststudentDescStdDob := mststudentFields[10].Descriptor()
	// mststudent.DefaultStdDob holds the default value on creation for the std_dob field.
	mststudent.DefaultStdDob = mststudentDescStdDob.Default.(func() time.Time)
	// mststudentDescStdEmail is the schema descriptor for std_email field.
	mststudentDescStdEmail := mststudentFields[11].Descriptor()
	// mststudent.StdEmailValidator is a validator for the "std_email" field. It is called by the builders before save.
	mststudent.StdEmailValidator = mststudentDescStdEmail.Validators[0].(func(string) error)
	// mststudentDescStdMobile is the schema descriptor for std_mobile field.
	mststudentDescStdMobile := mststudentFields[12].Descriptor()
	// mststudent.StdMobileValidator is a validator for the "std_mobile" field. It is called by the builders before save.
	mststudent.StdMobileValidator = mststudentDescStdMobile.Validators[0].(func(string) error)
	// mststudentDescStdFatherName is the schema descriptor for std_father_name field.
	mststudentDescStdFatherName := mststudentFields[13].Descriptor()
	// mststudent.DefaultStdFatherName holds the default value on creation for the std_father_name field.
	mststudent.DefaultStdFatherName = mststudentDescStdFatherName.Default.(string)
	// mststudentDescStdMotherName is the schema descriptor for std_mother_name field.
	mststudentDescStdMotherName := mststudentFields[14].Descriptor()
	// mststudent.DefaultStdMotherName holds the default value on creation for the std_mother_name field.
	mststudent.DefaultStdMotherName = mststudentDescStdMotherName.Default.(string)
}

const (
	Version = "v0.11.3-0.20220830071904-3b1b75b9d7a9"           // Version of ent codegen.
	Sum     = "h1:dxyBYasfOuLgAT0IuqSXNgDDJ9ra5C+Jc8a6VqVywWo=" // Sum of ent codegen.
)
