// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package admnumber

const (
	// Label holds the string label denoting the admnumber type in the database.
	Label = "adm_number"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAdmStartNo holds the string denoting the adm_start_no field in the database.
	FieldAdmStartNo = "adm_start_no"
	// FieldAdmCurrentNo holds the string denoting the adm_current_no field in the database.
	FieldAdmCurrentNo = "adm_current_no"
	// FieldIsPrefixed holds the string denoting the is_prefixed field in the database.
	FieldIsPrefixed = "is_prefixed"
	// FieldPrefixStr holds the string denoting the prefix_str field in the database.
	FieldPrefixStr = "prefix_str"
	// FieldSuffixStr holds the string denoting the suffix_str field in the database.
	FieldSuffixStr = "suffix_str"
	// FieldSeparator holds the string denoting the separator field in the database.
	FieldSeparator = "separator"
	// FieldPrefillWithZero holds the string denoting the prefill_with_zero field in the database.
	FieldPrefillWithZero = "prefill_with_zero"
	// FieldPrefillWidth holds the string denoting the prefill_width field in the database.
	FieldPrefillWidth = "prefill_width"
	// Table holds the table name of the admnumber in the database.
	Table = "adm_numbers"
)

// Columns holds all SQL columns for admnumber fields.
var Columns = []string{
	FieldID,
	FieldAdmStartNo,
	FieldAdmCurrentNo,
	FieldIsPrefixed,
	FieldPrefixStr,
	FieldSuffixStr,
	FieldSeparator,
	FieldPrefillWithZero,
	FieldPrefillWidth,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAdmStartNo holds the default value on creation for the "adm_start_no" field.
	DefaultAdmStartNo string
	// DefaultAdmCurrentNo holds the default value on creation for the "adm_current_no" field.
	DefaultAdmCurrentNo string
	// DefaultIsPrefixed holds the default value on creation for the "is_prefixed" field.
	DefaultIsPrefixed bool
	// DefaultPrefixStr holds the default value on creation for the "prefix_str" field.
	DefaultPrefixStr string
	// DefaultSuffixStr holds the default value on creation for the "suffix_str" field.
	DefaultSuffixStr string
	// DefaultSeparator holds the default value on creation for the "separator" field.
	DefaultSeparator string
	// DefaultPrefillWithZero holds the default value on creation for the "prefill_with_zero" field.
	DefaultPrefillWithZero bool
	// DefaultPrefillWidth holds the default value on creation for the "prefill_width" field.
	DefaultPrefillWidth int
	// PrefillWidthValidator is a validator for the "prefill_width" field. It is called by the builders before save.
	PrefillWidthValidator func(int) error
)
