// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"adm-num/ent/admnumber"
	"adm-num/ent/predicate"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdmNumberDelete is the builder for deleting a AdmNumber entity.
type AdmNumberDelete struct {
	config
	hooks    []Hook
	mutation *AdmNumberMutation
}

// Where appends a list predicates to the AdmNumberDelete builder.
func (and *AdmNumberDelete) Where(ps ...predicate.AdmNumber) *AdmNumberDelete {
	and.mutation.Where(ps...)
	return and
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (and *AdmNumberDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(and.hooks) == 0 {
		affected, err = and.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdmNumberMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			and.mutation = mutation
			affected, err = and.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(and.hooks) - 1; i >= 0; i-- {
			if and.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = and.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, and.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (and *AdmNumberDelete) ExecX(ctx context.Context) int {
	n, err := and.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (and *AdmNumberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: admnumber.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: admnumber.FieldID,
			},
		},
	}
	if ps := and.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, and.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// AdmNumberDeleteOne is the builder for deleting a single AdmNumber entity.
type AdmNumberDeleteOne struct {
	and *AdmNumberDelete
}

// Exec executes the deletion query.
func (ando *AdmNumberDeleteOne) Exec(ctx context.Context) error {
	n, err := ando.and.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{admnumber.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ando *AdmNumberDeleteOne) ExecX(ctx context.Context) {
	ando.and.ExecX(ctx)
}
