// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"adm-num/ent/admnumber"
	"adm-num/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdmNumberQuery is the builder for querying AdmNumber entities.
type AdmNumberQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AdmNumber
	loadTotal  []func(context.Context, []*AdmNumber) error
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AdmNumberQuery builder.
func (anq *AdmNumberQuery) Where(ps ...predicate.AdmNumber) *AdmNumberQuery {
	anq.predicates = append(anq.predicates, ps...)
	return anq
}

// Limit adds a limit step to the query.
func (anq *AdmNumberQuery) Limit(limit int) *AdmNumberQuery {
	anq.limit = &limit
	return anq
}

// Offset adds an offset step to the query.
func (anq *AdmNumberQuery) Offset(offset int) *AdmNumberQuery {
	anq.offset = &offset
	return anq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (anq *AdmNumberQuery) Unique(unique bool) *AdmNumberQuery {
	anq.unique = &unique
	return anq
}

// Order adds an order step to the query.
func (anq *AdmNumberQuery) Order(o ...OrderFunc) *AdmNumberQuery {
	anq.order = append(anq.order, o...)
	return anq
}

// First returns the first AdmNumber entity from the query.
// Returns a *NotFoundError when no AdmNumber was found.
func (anq *AdmNumberQuery) First(ctx context.Context) (*AdmNumber, error) {
	nodes, err := anq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{admnumber.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (anq *AdmNumberQuery) FirstX(ctx context.Context) *AdmNumber {
	node, err := anq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AdmNumber ID from the query.
// Returns a *NotFoundError when no AdmNumber ID was found.
func (anq *AdmNumberQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = anq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{admnumber.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (anq *AdmNumberQuery) FirstIDX(ctx context.Context) int {
	id, err := anq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AdmNumber entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AdmNumber entity is found.
// Returns a *NotFoundError when no AdmNumber entities are found.
func (anq *AdmNumberQuery) Only(ctx context.Context) (*AdmNumber, error) {
	nodes, err := anq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{admnumber.Label}
	default:
		return nil, &NotSingularError{admnumber.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (anq *AdmNumberQuery) OnlyX(ctx context.Context) *AdmNumber {
	node, err := anq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AdmNumber ID in the query.
// Returns a *NotSingularError when more than one AdmNumber ID is found.
// Returns a *NotFoundError when no entities are found.
func (anq *AdmNumberQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = anq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{admnumber.Label}
	default:
		err = &NotSingularError{admnumber.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (anq *AdmNumberQuery) OnlyIDX(ctx context.Context) int {
	id, err := anq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AdmNumbers.
func (anq *AdmNumberQuery) All(ctx context.Context) ([]*AdmNumber, error) {
	if err := anq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return anq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (anq *AdmNumberQuery) AllX(ctx context.Context) []*AdmNumber {
	nodes, err := anq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AdmNumber IDs.
func (anq *AdmNumberQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := anq.Select(admnumber.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (anq *AdmNumberQuery) IDsX(ctx context.Context) []int {
	ids, err := anq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (anq *AdmNumberQuery) Count(ctx context.Context) (int, error) {
	if err := anq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return anq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (anq *AdmNumberQuery) CountX(ctx context.Context) int {
	count, err := anq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (anq *AdmNumberQuery) Exist(ctx context.Context) (bool, error) {
	if err := anq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return anq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (anq *AdmNumberQuery) ExistX(ctx context.Context) bool {
	exist, err := anq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AdmNumberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (anq *AdmNumberQuery) Clone() *AdmNumberQuery {
	if anq == nil {
		return nil
	}
	return &AdmNumberQuery{
		config:     anq.config,
		limit:      anq.limit,
		offset:     anq.offset,
		order:      append([]OrderFunc{}, anq.order...),
		predicates: append([]predicate.AdmNumber{}, anq.predicates...),
		// clone intermediate query.
		sql:    anq.sql.Clone(),
		path:   anq.path,
		unique: anq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AdmStartNo string `json:"adm_start_no,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AdmNumber.Query().
//		GroupBy(admnumber.FieldAdmStartNo).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (anq *AdmNumberQuery) GroupBy(field string, fields ...string) *AdmNumberGroupBy {
	grbuild := &AdmNumberGroupBy{config: anq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := anq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return anq.sqlQuery(ctx), nil
	}
	grbuild.label = admnumber.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AdmStartNo string `json:"adm_start_no,omitempty"`
//	}
//
//	client.AdmNumber.Query().
//		Select(admnumber.FieldAdmStartNo).
//		Scan(ctx, &v)
func (anq *AdmNumberQuery) Select(fields ...string) *AdmNumberSelect {
	anq.fields = append(anq.fields, fields...)
	selbuild := &AdmNumberSelect{AdmNumberQuery: anq}
	selbuild.label = admnumber.Label
	selbuild.flds, selbuild.scan = &anq.fields, selbuild.Scan
	return selbuild
}

func (anq *AdmNumberQuery) prepareQuery(ctx context.Context) error {
	for _, f := range anq.fields {
		if !admnumber.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if anq.path != nil {
		prev, err := anq.path(ctx)
		if err != nil {
			return err
		}
		anq.sql = prev
	}
	return nil
}

func (anq *AdmNumberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AdmNumber, error) {
	var (
		nodes = []*AdmNumber{}
		_spec = anq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AdmNumber).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AdmNumber{config: anq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(anq.modifiers) > 0 {
		_spec.Modifiers = anq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, anq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range anq.loadTotal {
		if err := anq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (anq *AdmNumberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := anq.querySpec()
	if len(anq.modifiers) > 0 {
		_spec.Modifiers = anq.modifiers
	}
	_spec.Node.Columns = anq.fields
	if len(anq.fields) > 0 {
		_spec.Unique = anq.unique != nil && *anq.unique
	}
	return sqlgraph.CountNodes(ctx, anq.driver, _spec)
}

func (anq *AdmNumberQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := anq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (anq *AdmNumberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   admnumber.Table,
			Columns: admnumber.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: admnumber.FieldID,
			},
		},
		From:   anq.sql,
		Unique: true,
	}
	if unique := anq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := anq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, admnumber.FieldID)
		for i := range fields {
			if fields[i] != admnumber.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := anq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := anq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := anq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := anq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (anq *AdmNumberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(anq.driver.Dialect())
	t1 := builder.Table(admnumber.Table)
	columns := anq.fields
	if len(columns) == 0 {
		columns = admnumber.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if anq.sql != nil {
		selector = anq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if anq.unique != nil && *anq.unique {
		selector.Distinct()
	}
	for _, m := range anq.modifiers {
		m(selector)
	}
	for _, p := range anq.predicates {
		p(selector)
	}
	for _, p := range anq.order {
		p(selector)
	}
	if offset := anq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := anq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (anq *AdmNumberQuery) ForUpdate(opts ...sql.LockOption) *AdmNumberQuery {
	if anq.driver.Dialect() == dialect.Postgres {
		anq.Unique(false)
	}
	anq.modifiers = append(anq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return anq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (anq *AdmNumberQuery) ForShare(opts ...sql.LockOption) *AdmNumberQuery {
	if anq.driver.Dialect() == dialect.Postgres {
		anq.Unique(false)
	}
	anq.modifiers = append(anq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return anq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (anq *AdmNumberQuery) Modify(modifiers ...func(s *sql.Selector)) *AdmNumberSelect {
	anq.modifiers = append(anq.modifiers, modifiers...)
	return anq.Select()
}

// AdmNumberGroupBy is the group-by builder for AdmNumber entities.
type AdmNumberGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (angb *AdmNumberGroupBy) Aggregate(fns ...AggregateFunc) *AdmNumberGroupBy {
	angb.fns = append(angb.fns, fns...)
	return angb
}

// Scan applies the group-by query and scans the result into the given value.
func (angb *AdmNumberGroupBy) Scan(ctx context.Context, v any) error {
	query, err := angb.path(ctx)
	if err != nil {
		return err
	}
	angb.sql = query
	return angb.sqlScan(ctx, v)
}

func (angb *AdmNumberGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range angb.fields {
		if !admnumber.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := angb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := angb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (angb *AdmNumberGroupBy) sqlQuery() *sql.Selector {
	selector := angb.sql.Select()
	aggregation := make([]string, 0, len(angb.fns))
	for _, fn := range angb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(angb.fields)+len(angb.fns))
		for _, f := range angb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(angb.fields...)...)
}

// AdmNumberSelect is the builder for selecting fields of AdmNumber entities.
type AdmNumberSelect struct {
	*AdmNumberQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ans *AdmNumberSelect) Scan(ctx context.Context, v any) error {
	if err := ans.prepareQuery(ctx); err != nil {
		return err
	}
	ans.sql = ans.AdmNumberQuery.sqlQuery(ctx)
	return ans.sqlScan(ctx, v)
}

func (ans *AdmNumberSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := ans.sql.Query()
	if err := ans.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ans *AdmNumberSelect) Modify(modifiers ...func(s *sql.Selector)) *AdmNumberSelect {
	ans.modifiers = append(ans.modifiers, modifiers...)
	return ans
}
