//go:build ignore
// +build ignore

package main

import (
	"log"
	"adm-num/utils"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
	"firebase.google.com/go/v4/auth"
)

func main() {
	ex, err := entgql.NewExtension(
		entgql.WithWhereFilters(true),
		entgql.WithConfigPath("../gqlgen.yml"),
		entgql.WithSchemaPath("../graphql/schema/ent.gql"),
	)
	if err != nil {
		log.Fatalf("creating entgql extension: %v", err)
	}
	opts := []entc.Option{
		entc.Extensions(ex),
		entc.TemplateDir("./template"),
		entc.FeatureNames("privacy"),
		entc.FeatureNames("schema/snapshot"),
		entc.FeatureNames("sql/modifier"),
		entc.FeatureNames("entql"),
		entc.FeatureNames("sql/upsert"),
		entc.FeatureNames("sql/versioned-migration"),
		entc.FeatureNames("namedges"),
		entc.FeatureNames("sql/lock"),
		entc.FeatureNames("sql/execquery"),

		entc.Dependency(entc.DependencyType(&auth.Client{})),
		entc.Dependency(entc.DependencyType(&utils.Config{})),
	}
	if err := entc.Generate("./schema", &gen.Config{
		Header: `
			// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
			// Code generated by entc, DO NOT EDIT.
		`,
	}, opts...); err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}
}
