// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"adm-num/ent/mststudent"
	"adm-num/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MstStudentQuery is the builder for querying MstStudent entities.
type MstStudentQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.MstStudent
	loadTotal  []func(context.Context, []*MstStudent) error
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MstStudentQuery builder.
func (msq *MstStudentQuery) Where(ps ...predicate.MstStudent) *MstStudentQuery {
	msq.predicates = append(msq.predicates, ps...)
	return msq
}

// Limit adds a limit step to the query.
func (msq *MstStudentQuery) Limit(limit int) *MstStudentQuery {
	msq.limit = &limit
	return msq
}

// Offset adds an offset step to the query.
func (msq *MstStudentQuery) Offset(offset int) *MstStudentQuery {
	msq.offset = &offset
	return msq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (msq *MstStudentQuery) Unique(unique bool) *MstStudentQuery {
	msq.unique = &unique
	return msq
}

// Order adds an order step to the query.
func (msq *MstStudentQuery) Order(o ...OrderFunc) *MstStudentQuery {
	msq.order = append(msq.order, o...)
	return msq
}

// First returns the first MstStudent entity from the query.
// Returns a *NotFoundError when no MstStudent was found.
func (msq *MstStudentQuery) First(ctx context.Context) (*MstStudent, error) {
	nodes, err := msq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mststudent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (msq *MstStudentQuery) FirstX(ctx context.Context) *MstStudent {
	node, err := msq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MstStudent ID from the query.
// Returns a *NotFoundError when no MstStudent ID was found.
func (msq *MstStudentQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = msq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mststudent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (msq *MstStudentQuery) FirstIDX(ctx context.Context) int {
	id, err := msq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MstStudent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MstStudent entity is found.
// Returns a *NotFoundError when no MstStudent entities are found.
func (msq *MstStudentQuery) Only(ctx context.Context) (*MstStudent, error) {
	nodes, err := msq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mststudent.Label}
	default:
		return nil, &NotSingularError{mststudent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (msq *MstStudentQuery) OnlyX(ctx context.Context) *MstStudent {
	node, err := msq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MstStudent ID in the query.
// Returns a *NotSingularError when more than one MstStudent ID is found.
// Returns a *NotFoundError when no entities are found.
func (msq *MstStudentQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = msq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mststudent.Label}
	default:
		err = &NotSingularError{mststudent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (msq *MstStudentQuery) OnlyIDX(ctx context.Context) int {
	id, err := msq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MstStudents.
func (msq *MstStudentQuery) All(ctx context.Context) ([]*MstStudent, error) {
	if err := msq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return msq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (msq *MstStudentQuery) AllX(ctx context.Context) []*MstStudent {
	nodes, err := msq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MstStudent IDs.
func (msq *MstStudentQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := msq.Select(mststudent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (msq *MstStudentQuery) IDsX(ctx context.Context) []int {
	ids, err := msq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (msq *MstStudentQuery) Count(ctx context.Context) (int, error) {
	if err := msq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return msq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (msq *MstStudentQuery) CountX(ctx context.Context) int {
	count, err := msq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (msq *MstStudentQuery) Exist(ctx context.Context) (bool, error) {
	if err := msq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return msq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (msq *MstStudentQuery) ExistX(ctx context.Context) bool {
	exist, err := msq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MstStudentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (msq *MstStudentQuery) Clone() *MstStudentQuery {
	if msq == nil {
		return nil
	}
	return &MstStudentQuery{
		config:     msq.config,
		limit:      msq.limit,
		offset:     msq.offset,
		order:      append([]OrderFunc{}, msq.order...),
		predicates: append([]predicate.MstStudent{}, msq.predicates...),
		// clone intermediate query.
		sql:    msq.sql.Clone(),
		path:   msq.path,
		unique: msq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FirstName string `json:"first_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MstStudent.Query().
//		GroupBy(mststudent.FieldFirstName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (msq *MstStudentQuery) GroupBy(field string, fields ...string) *MstStudentGroupBy {
	grbuild := &MstStudentGroupBy{config: msq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := msq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return msq.sqlQuery(ctx), nil
	}
	grbuild.label = mststudent.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FirstName string `json:"first_name,omitempty"`
//	}
//
//	client.MstStudent.Query().
//		Select(mststudent.FieldFirstName).
//		Scan(ctx, &v)
func (msq *MstStudentQuery) Select(fields ...string) *MstStudentSelect {
	msq.fields = append(msq.fields, fields...)
	selbuild := &MstStudentSelect{MstStudentQuery: msq}
	selbuild.label = mststudent.Label
	selbuild.flds, selbuild.scan = &msq.fields, selbuild.Scan
	return selbuild
}

func (msq *MstStudentQuery) prepareQuery(ctx context.Context) error {
	for _, f := range msq.fields {
		if !mststudent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if msq.path != nil {
		prev, err := msq.path(ctx)
		if err != nil {
			return err
		}
		msq.sql = prev
	}
	return nil
}

func (msq *MstStudentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MstStudent, error) {
	var (
		nodes = []*MstStudent{}
		_spec = msq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MstStudent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MstStudent{config: msq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(msq.modifiers) > 0 {
		_spec.Modifiers = msq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, msq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range msq.loadTotal {
		if err := msq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (msq *MstStudentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := msq.querySpec()
	if len(msq.modifiers) > 0 {
		_spec.Modifiers = msq.modifiers
	}
	_spec.Node.Columns = msq.fields
	if len(msq.fields) > 0 {
		_spec.Unique = msq.unique != nil && *msq.unique
	}
	return sqlgraph.CountNodes(ctx, msq.driver, _spec)
}

func (msq *MstStudentQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := msq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (msq *MstStudentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   mststudent.Table,
			Columns: mststudent.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: mststudent.FieldID,
			},
		},
		From:   msq.sql,
		Unique: true,
	}
	if unique := msq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := msq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mststudent.FieldID)
		for i := range fields {
			if fields[i] != mststudent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := msq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := msq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := msq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := msq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (msq *MstStudentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(msq.driver.Dialect())
	t1 := builder.Table(mststudent.Table)
	columns := msq.fields
	if len(columns) == 0 {
		columns = mststudent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if msq.sql != nil {
		selector = msq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if msq.unique != nil && *msq.unique {
		selector.Distinct()
	}
	for _, m := range msq.modifiers {
		m(selector)
	}
	for _, p := range msq.predicates {
		p(selector)
	}
	for _, p := range msq.order {
		p(selector)
	}
	if offset := msq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := msq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (msq *MstStudentQuery) ForUpdate(opts ...sql.LockOption) *MstStudentQuery {
	if msq.driver.Dialect() == dialect.Postgres {
		msq.Unique(false)
	}
	msq.modifiers = append(msq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return msq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (msq *MstStudentQuery) ForShare(opts ...sql.LockOption) *MstStudentQuery {
	if msq.driver.Dialect() == dialect.Postgres {
		msq.Unique(false)
	}
	msq.modifiers = append(msq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return msq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (msq *MstStudentQuery) Modify(modifiers ...func(s *sql.Selector)) *MstStudentSelect {
	msq.modifiers = append(msq.modifiers, modifiers...)
	return msq.Select()
}

// MstStudentGroupBy is the group-by builder for MstStudent entities.
type MstStudentGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (msgb *MstStudentGroupBy) Aggregate(fns ...AggregateFunc) *MstStudentGroupBy {
	msgb.fns = append(msgb.fns, fns...)
	return msgb
}

// Scan applies the group-by query and scans the result into the given value.
func (msgb *MstStudentGroupBy) Scan(ctx context.Context, v any) error {
	query, err := msgb.path(ctx)
	if err != nil {
		return err
	}
	msgb.sql = query
	return msgb.sqlScan(ctx, v)
}

func (msgb *MstStudentGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range msgb.fields {
		if !mststudent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := msgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := msgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (msgb *MstStudentGroupBy) sqlQuery() *sql.Selector {
	selector := msgb.sql.Select()
	aggregation := make([]string, 0, len(msgb.fns))
	for _, fn := range msgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(msgb.fields)+len(msgb.fns))
		for _, f := range msgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(msgb.fields...)...)
}

// MstStudentSelect is the builder for selecting fields of MstStudent entities.
type MstStudentSelect struct {
	*MstStudentQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (mss *MstStudentSelect) Scan(ctx context.Context, v any) error {
	if err := mss.prepareQuery(ctx); err != nil {
		return err
	}
	mss.sql = mss.MstStudentQuery.sqlQuery(ctx)
	return mss.sqlScan(ctx, v)
}

func (mss *MstStudentSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := mss.sql.Query()
	if err := mss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mss *MstStudentSelect) Modify(modifiers ...func(s *sql.Selector)) *MstStudentSelect {
	mss.modifiers = append(mss.modifiers, modifiers...)
	return mss
}
