// Copyright 2021-present Eduate Pvt Ltd. All rights reserved.
// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdmNumber is the predicate function for admnumber builders.
type AdmNumber func(*sql.Selector)

// MstStudent is the predicate function for mststudent builders.
type MstStudent func(*sql.Selector)
